"use client";

import { useEffect, useState } from "react";

type Campaign = { id?: string; name: string; channel: string; status: string; objective: string; audience: string; start_date: string | null; end_date: string | null; budget_cents: number | null; notes: string };
const blank: Campaign = { name: "", channel: "organic", status: "draft", objective: "", audience: "", start_date: null, end_date: null, budget_cents: null, notes: "" };

export default function MarketingPage() {
  const [items, setItems] = useState<Campaign[]>([]); const [form, setForm] = useState<Campaign>(blank); const [editing, setEditing] = useState<string | undefined>(); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/marketing").then(r => r.json()).then(d => Array.isArray(d) ? setItems(d) : setError(d.error || "Unable to load campaigns")); }, []);
  const update = (key: keyof Campaign, value: string | number | null) => setForm({ ...form, [key]: value });
  async function save(e: React.FormEvent) { e.preventDefault(); setError(""); const res = await fetch("/api/marketing", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, id: editing }) }); const d = await res.json(); if (!res.ok) return setError(d.error || "Save failed"); setItems(editing ? items.map(i => i.id === editing ? d : i) : [d, ...items]); setForm(blank); setEditing(undefined); }
  function edit(item: Campaign) { setEditing(item.id); setForm(item); }
  async function remove(id?: string) { if (!id || !confirm("Delete this campaign?")) return; await fetch("/api/marketing", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); setItems(items.filter(i => i.id !== id)); }
  return <div className="min-h-screen bg-neutral-100 p-8"><div className="max-w-5xl mx-auto"><a href="/admin/dashboard" className="text-lg text-neutral-600 hover:text-amber-600 font-bold">← Dashboard</a><h1 className="text-4xl font-bold text-neutral-900 mt-2">Marketing</h1><p className="text-lg text-neutral-600 font-medium mb-8">Plan campaigns, offers, and distribution without publishing automatically.</p>
    {error && <div className="bg-red-100 border-2 border-red-400 p-4 mb-5 font-bold">{error}</div>}
    <form onSubmit={save} className="bg-white border-[3px] border-neutral-500 p-6 mb-8 grid md:grid-cols-2 gap-4"><h2 className="md:col-span-2 text-2xl font-bold">{editing ? "Edit campaign" : "New campaign"}</h2>{([['name','Campaign name'],['objective','Objective'],['audience','Audience'],['notes','Notes']] as const).map(([key,label]) => <label key={key} className="flex flex-col gap-1 font-bold">{label}{key === 'notes' || key === 'objective' || key === 'audience' ? <textarea value={String(form[key] || "")} onChange={e => update(key,e.target.value)} className="border-2 border-neutral-400 p-3" rows={key === 'notes' ? 3 : 2} /> : <input value={String(form[key] || "")} onChange={e => update(key,e.target.value)} className="border-2 border-neutral-400 p-3" required />}</label>)}<label className="flex flex-col gap-1 font-bold">Channel<select value={form.channel} onChange={e => update('channel',e.target.value)} className="border-2 border-neutral-400 p-3"><option>organic</option><option>email</option><option>social</option><option>paid_search</option><option>partner</option></select></label><label className="flex flex-col gap-1 font-bold">Status<select value={form.status} onChange={e => update('status',e.target.value)} className="border-2 border-neutral-400 p-3"><option>draft</option><option>planned</option><option>active</option><option>paused</option><option>complete</option></select></label><label className="flex flex-col gap-1 font-bold">Start date<input type="date" value={form.start_date || ""} onChange={e => update('start_date',e.target.value || null)} className="border-2 border-neutral-400 p-3" /></label><label className="flex flex-col gap-1 font-bold">End date<input type="date" value={form.end_date || ""} onChange={e => update('end_date',e.target.value || null)} className="border-2 border-neutral-400 p-3" /></label><label className="flex flex-col gap-1 font-bold">Budget ($)<input type="number" min="0" step="0.01" value={form.budget_cents == null ? "" : form.budget_cents / 100} onChange={e => update('budget_cents',e.target.value === "" ? null : Math.round(Number(e.target.value) * 100))} className="border-2 border-neutral-400 p-3" /></label><div className="md:col-span-2 flex gap-3"><button className="bg-amber-500 px-6 py-3 font-bold">{editing ? "Save changes" : "Add campaign"}</button>{editing && <button type="button" onClick={() => {setEditing(undefined);setForm(blank);}} className="border-2 border-neutral-400 px-6 py-3 font-bold">Cancel</button>}</div></form>
    <div className="space-y-4">{items.map(item => <article key={item.id} className="bg-white border-[3px] border-neutral-300 p-6"><div className="flex justify-between gap-4"><div><h2 className="text-2xl font-bold">{item.name}</h2><p className="text-neutral-600 font-medium">{item.channel} · {item.status}{item.start_date ? ` · ${item.start_date}` : ""}{item.end_date ? ` to ${item.end_date}` : ""}</p></div><div className="flex gap-3"><button onClick={() => edit(item)} className="font-bold text-amber-700">Edit</button><button onClick={() => remove(item.id)} className="font-bold text-red-600">Delete</button></div></div>{item.objective && <p className="mt-4"><strong>Objective:</strong> {item.objective}</p>}{item.audience && <p><strong>Audience:</strong> {item.audience}</p>}{item.budget_cents != null && <p><strong>Budget:</strong> ${(item.budget_cents / 100).toFixed(2)}</p>}{item.notes && <p className="mt-2 whitespace-pre-wrap text-neutral-600">{item.notes}</p>}</article>)}</div>
  </div></div>;
}
